version: '2'

services:
  backend-frontend-go:
    container_name: backend-frontend-go
    image: backend-frontend-backend:0.0.8
    build: .
    volumes:
    - ./frontend:/app/frontend
    ports:
      - 2022:2022
    restart: always